### ISSUE TITLE
Asks for a MM mod as a dependencie

### ISSUE THREAD

**Issue by GlitchTDG** [elysian-mods/ClassicAdventure#1]
Loading the mod prints out the following 

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install mm, version 2.3 or later.
More details:
	 - Mod 'Classic Adventure' (classic_adventure) 1.0 requires version 2.3 or later of mm, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by kg583** [comment]
You need to install [MM](https://github.com/Chocohead/Fabric-ASM).

**Comment by GlitchTDG** [comment]
> You need to install [MM](https://github.com/Chocohead/Fabric-ASM).

right... thx for the link but his releases go only up to 2.0 and the mod is asking for 2.3. I tried grafting a 2.3 version ( got the 2.0 and pasted the matching 2.3 files inside ), the launcher recognizes it as 2.3, the game starts but then on preparing for world creation the game crashes.

**Comment by kg583** [comment]
Hmmm, well it should've been bundled with the jar anyway, but it just wasn't. The 1.20.4 release should work.
